name: Deploy

on: 
  release:
    types:
      - published

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install poetry
      - name: Install project dependencies
        run: poetry install
      - name: Echo
        run: echo "teste"
      - name: Update versino in pyproject.toml
        run: |
          sed -i "s/version = .*/version = \"$GITHUB_REF_NAME\"/g" pyproject.toml
      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
          message: 'Update version in pyproject.toml'
      - name: Build & Publish
        run: |
          poetry build
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
          
          
